---
- name: Add NVIDIA Container Toolkit GPG Key
  apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present
  when: ansible_os_family == 'Debian'

- name: Add NVIDIA Container Toolkit Repository
  get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
  when: ansible_os_family == 'Debian'

- name: Install NVIDIA Container Toolkit and dependencies
  apt:
    name:
      - nvidia-container-toolkit
      - runc
    state: present
  register: apt_res
  retries: 5
  delay: 10
  until: apt_res is success
  when: ansible_os_family == 'Debian'

- name: Configure Containerd for NVIDIA (K3s)
  template:
    src: config.toml.tmpl.j2
    dest: /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
    owner: root
    group: root
    mode: '0644'

- name: Restart K3s Agent to pick up changes
  service:
    name: k3s-agent
    state: restarted
